version: '2'
services:

    # Application container
    php:
        image: pedrofaria/php:7-apache
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
        ports:
            - "3000:80"
        environment:
            DEBUG: 'true'
